kind: pipeline
name: TwoggCI

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
  - go test -v ./...

- name: integration
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...
  when:
    branch:
    - master

- name: publish-api-docker
    image: plugins/docker:1.12
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: twogghub/go-droneci
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: ./
