kind: pipeline
name: TwoggCI

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
  - echo -n "1.1" > .tags
  
- name: testing
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: twogghub/go-droneci
  when:
    branch:
    - master
