kind: pipeline
name: Pipeline

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
  
- name: testing
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...

- name: notify
  image: drillster/drone-email
  settings: 
    host: smtp
    username: user
    password: pwd
    port: 25
    skip_verify: true
    from: pipeline@go-droneci.com
    when:
      status: [ changed, failure ]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: twogghub/go-droneci
    tags:
      - 1.0.2
      - latest
  when:
    branch:
    - master

services:
- name: smtp
  image: catatnight/postfix
  environment:
    ports: 25
    maildomain: go-droneci.com
    smtp_user: user:pwd
    messageSizeLimit: 40960000
    mailboxSizeLimit: 40960000

