kind: pipeline
name: TwoggCI

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
  - echo -n "1.0, " > .tags
  
- name: testing
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...

- name: publish
  image: plugins/docker
  username: ${DOCKER_USERNAME}
  password: ${DOCKER_PASSWORD}
  repo: twogghub/go-droneci
  build_args:
    - TARGET_IMAGE=twogghub/go-droneci
    - TAG=1.0
  when:
    branch:
    - master
