kind: pipeline
name: TwoggCI

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
  - go test -v ./...
    
- name: integration
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...
  when:
    branch:
    - master

- name: publish
  image: plugins/docker
  username: ${DOCKER_USERNAME}
  password: ${DOCKER_PASSWORD}
  repo: twogghub/go-droneci
  tags: 1
  
