kind: pipeline
name: TwoggCI

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
  - go test -v ./...

- name: integration
  image: golang
  commands:
  - go test -v ./...
  when:
    event:
    - pull_request
